version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: auth_task_db 
    networks:
      - mernstack
   
  backend:
    container_name: nodejs
    image: cloudwithrk/nodebackend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mernstack
  fronted:
    container_name: reactjs
    image: cloudwithrk/reactfrontend:latest
    ports:
      - 3000:3000
    networks:
      - mernstack
  
    
    
volumes:
  mysql_data:
networks:
  mernstack: